export type Product = {
  id: string;
  sku: string;
  name: string;
  shortDesc: string;
  fullDesc: string;
  price: number;
  category: "Men's Dress" | "Women's Casual" | "Men's Athletic" | "Women's Boots" | "Men's Boots" | "Women's Sandals" | "Men's Casual" | "Women's Dress" | "Men's Outdoor" | "Women's Athletic" | "Men's Sandals";
};

export const products: Product[] = [
  {
    id: "1",
    sku: "WZ-M-001",
    name: "Men's Classic Oxford",
    shortDesc: "Timeless black leather dress shoe.",
    fullDesc: "Step into the boardroom with confidence. Crafted from premium full-grain leather, this Oxford features a cushioned insole and a durable rubber outsole for all-day comfort without compromising on a sharp, professional aesthetic.",
    price: 120.00,
    category: "Men's Dress",
  },
  {
    id: "2",
    sku: "WZ-W-002",
    name: "Women's Zen Loafer",
    shortDesc: "Slip-on everyday comfort loafer.",
    fullDesc: "The ultimate everyday shoe. Made from butter-soft suede with a flexible sole, this minimalist loafer molds to your foot for a custom fit. Perfect for the office or weekend errands.",
    price: 85.00,
    category: "Women's Casual",
  },
  {
    id: "3",
    sku: "WZ-M-003",
    name: "Men's Cloud-Step Sneaker",
    shortDesc: "Lightweight athletic running shoe.",
    fullDesc: "Experience weightless movement. Featuring a breathable mesh upper and our signature shock-absorbing EVA midsole, these sneakers are designed for long walks, light runs, and everything in between.",
    price: 95.00,
    category: "Men's Athletic",
  },
  {
    id: "4",
    sku: "WZ-W-004",
    name: "Women's Essential Ankle Boot",
    shortDesc: "Sleek black leather bootie.",
    fullDesc: "A wardrobe staple for any season. Features a low, stacked block heel for stability, an inner zipper for easy wear, and premium water-resistant leather. Transitions seamlessly from day to night.",
    price: 135.00,
    category: "Women's Boots",
  },
  {
    id: "5",
    sku: "WZ-M-005",
    name: "Men's Suede Chelsea Boot",
    shortDesc: "Classic pull-on ankle boot.",
    fullDesc: "Effortlessly stylish and remarkably comfortable. This Chelsea boot features elastic side panels, a pull tab, and a cushioned footbed, all wrapped in luxurious, weather-treated suede.",
    price: 140.00,
    category: "Men's Boots",
  },
  {
    id: "6",
    sku: "WZ-W-006",
    name: "Women's Everyday Slip-On",
    shortDesc: "Canvas casual walking shoe.",
    fullDesc: "Simple, breathable, and incredibly comfortable. These canvas slip-ons feature a padded collar and a memory foam insole, making them your go-to pair for busy days on your feet.",
    price: 60.00,
    category: "Women's Casual",
  },
  {
    id: "7",
    sku: "WZ-M-007",
    name: "Men's Breathable Runner",
    shortDesc: "High-performance athletic shoe.",
    fullDesc: "Engineered for endurance. This runner offers targeted arch support, a deeply treaded outsole for grip, and a knit upper that keeps your feet cool during intense workouts.",
    price: 110.00,
    category: "Men's Athletic",
  },
  {
    id: "8",
    sku: "WZ-W-008",
    name: "Women's Strappy Sandal",
    shortDesc: "Elegant summer leather sandal.",
    fullDesc: "Minimalist design meets all-day support. Featuring soft leather straps that won't dig in and a gently contoured footbed to support your arches during warm-weather strolls.",
    price: 75.00,
    category: "Women's Sandals",
  },
  {
    id: "9",
    sku: "WZ-M-009",
    name: "Men's Minimalist Sneaker",
    shortDesc: "Premium black leather sneaker.",
    fullDesc: "The perfect hybrid of casual and dressed-up. This low-profile leather sneaker features tonal stitching and a contrasting white rubber sole for a clean, modern look.",
    price: 105.00,
    category: "Men's Casual",
  },
  {
    id: "10",
    sku: "WZ-W-010",
    name: "Women's Block Heel Pump",
    shortDesc: "Comfortable office-ready heel.",
    fullDesc: "Redefining the work heel. Designed with a wider toe box, targeted heel cushioning, and a sturdy 2-inch block heel so you can walk through your workday without the ache.",
    price: 95.00,
    category: "Women's Dress",
  },
  {
    id: "11",
    sku: "WZ-M-011",
    name: "Men's Trail Trekker",
    shortDesc: "Rugged outdoor hiking shoe.",
    fullDesc: "Built for the adventurous spirit. Features a waterproof exterior, reinforced toe caps, and deep-lugged outsoles to provide superior traction on uneven terrain.",
    price: 130.00,
    category: "Men's Outdoor",
  },
  {
    id: "12",
    sku: "WZ-W-012",
    name: "Women's Platform Sneaker",
    shortDesc: "Trendy elevated casual shoe.",
    fullDesc: "Add a little height to your step without sacrificing comfort. These canvas sneakers feature a 1.5-inch platform sole and orthotic-friendly removable insoles.",
    price: 80.00,
    category: "Women's Casual",
  },
  {
    id: "13",
    sku: "WZ-M-013",
    name: "Men's Formal Brogue",
    shortDesc: "Detailed wingtip leather shoe.",
    fullDesc: "A masterclass in craftsmanship. These wingtip brogues feature intricate perforations, a hand-polished finish, and a cork-cushioned footbed that molds to your stride over time.",
    price: 145.00,
    category: "Men's Dress",
  },
  {
    id: "14",
    sku: "WZ-W-014",
    name: "Women's Knit Walking Shoe",
    shortDesc: "Ultra-flexible stretch sneaker.",
    fullDesc: "Fits like a sock, supports like a sneaker. The engineered knit upper expands and contracts with your foot, while the ultra-light sole makes you feel like you're walking on air.",
    price: 90.00,
    category: "Women's Athletic",
  },
  {
    id: "15",
    sku: "WZ-M-015",
    name: "Men's Comfort Slide",
    shortDesc: "Premium contoured summer slide.",
    fullDesc: "Relaxation for your feet. Whether you're by the pool or lounging at home, these slides offer a molded EVA footbed that supports your arches and cradles your heel.",
    price: 45.00,
    category: "Men's Sandals",
  },
];